version: 2

updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  rebase-strategy: "auto"
  groups:
    patch-npm-dependencies:
      # NPM: Only group minor and patch updates (we want to carefully review major updates)
      update-types: [patch]
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  rebase-strategy: "auto"
  groups:
    minor-actions-dependencies:
      # GitHub Actions: Only group minor and patch updates (we want to carefully review major updates)
      update-types: [minor, patch]
